How to I define a join table?
like this!

Last login: Fri Feb 28 09:17:25 on ttys000
ruby-2.0.0-p247 is not installed.
To install do: 'rvm install ruby-2.0.0-p247'
Taras-MacBook-Air:hacker_news tlroys$ rake generate:spec NAME="Comment"
Creating /Users/tlroys/Desktop/ThursdayProjects/hacker_news/spec/comment_spec.rb
Taras-MacBook-Air:hacker_news tlroys$ rspec
/Users/tlroys/Desktop/ThursdayProjects/hacker_news/spec/comment_spec.rb:3:in `<top (required)>': uninitialized constant Comment (NameError)
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `block in load_spec_files'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `each'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load_spec_files'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:22:in `run'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `block in autorun'
Taras-MacBook-Air:hacker_news tlroys$ rake generate:model NAME="Comment"
Creating /Users/tlroys/Desktop/ThursdayProjects/hacker_news/app/models/comment.rb
Taras-MacBook-Air:hacker_news tlroys$ rake -T
rake console             # Start IRB with application environment loaded
rake db:create           # Create the database at hacker_news_development
rake db:drop             # Drop the database at hacker_news_development
rake db:hard_reset       # drops, creates, migrates, and seeds test database
rake db:migrate          # Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog).
rake db:seed             # Populate the database with dummy data by running db/seeds.rb
rake db:version          # Returns the current schema version number
rake generate:migration  # Create an empty migration in db/migrate, e.g., rake generate:migration NAME=create_tasks
rake generate:model      # Create an empty model in app/models, e.g., rake generate:model NAME=User
rake generate:spec       # Create an empty model spec in spec, e.g., rake generate:spec NAME=user
rake spec                # Run the specs
Taras-MacBook-Air:hacker_news tlroys$ rspec
**........*

Pending:
  Join Table Associations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  Comment add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/comment_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Finished in 1.72 seconds
11 examples, 0 failures, 3 pending
Taras-MacBook-Air:hacker_news tlroys$ rspec
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load': /Users/tlroys/Desktop/ThursdayProjects/hacker_news/spec/comment_spec.rb:8: syntax error, unexpected keyword_end, expecting $end (SyntaxError)
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `block in load'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `block in load_spec_files'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `each'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load_spec_files'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:22:in `run'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `block in autorun'
Taras-MacBook-Air:hacker_news tlroys$ rspec
*F........*

Pending:
  Join Table Associations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Comment should have user_id, a post_id, a time created, and a content
     Failure/Error: expect(false).to eq(true)

       expected: true
            got: false

       (compared using ==)
     # ./spec/comment_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 1.66 seconds
11 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/comment_spec.rb:4 # Comment should have user_id, a post_id, a time created, and a content
Taras-MacBook-Air:hacker_news tlroys$ rspec
*F........*

Pending:
  Join Table Associations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Comment should have user_id, a post_id, a time created, and a content
     Failure/Error: first_post = Post.create(content)
     NameError:
       undefined local variable or method `content' for #<RSpec::Core::ExampleGroup::Nested_2:0x007ffb6abf1f90>
     # ./spec/comment_spec.rb:14:in `block (2 levels) in <top (required)>'

Finished in 1.85 seconds
11 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/comment_spec.rb:4 # Comment should have user_id, a post_id, a time created, and a content
Taras-MacBook-Air:hacker_news tlroys$ rspec
*F........*

Pending:
  Join Table Associations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Comment should have user_id, a post_id, a time created, and a content
     Failure/Error: first_post = Comment.create(comment_content)
     ActiveRecord::StatementInvalid:
       PG::Error: ERROR:  relation "comments" does not exist
       LINE 5:              WHERE a.attrelid = '"comments"'::regclass
                                               ^
       :             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                            pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                     FROM pg_attribute a LEFT JOIN pg_attrdef d
                       ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                    WHERE a.attrelid = '"comments"'::regclass
                      AND a.attnum > 0 AND NOT a.attisdropped
                    ORDER BY a.attnum
     # ./spec/comment_spec.rb:14:in `block (2 levels) in <top (required)>'

Finished in 1.9 seconds
11 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/comment_spec.rb:4 # Comment should have user_id, a post_id, a time created, and a content
Taras-MacBook-Air:hacker_news tlroys$ rake generate:migration NAME=create_comments
Creating /Users/tlroys/Desktop/ThursdayProjects/hacker_news/db/migrate/20140228093656_create_comments.rb
Taras-MacBook-Air:hacker_news tlroys$ echo "When you have a ton of tests, it goes through all of them. You only want the first test that fails. You can run something called fail fast, so that you can stop the suite and fix the bugs.  Fail-fast is like a medical doctor who fixes the spurting wound because it's the first thing he sees instead of doing a full physical exam before fixing the spurting wound."
When you have a ton of tests, it goes through all of them. You only want the first test that fails. You can run something called fail fast, so that you can stop the suite and fix the bugs.  Fail-fast is like a medical doctor who fixes the spurting wound because it's the first thing he sees instead of doing a full physical exam before fixing the spurting wound.
Taras-MacBook-Air:hacker_news tlroys$ rspec --fail-fast*FPending:
  Join Table Associations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4

Failures:

  1) Comment should have user_id, a post_id, a time created, and a content
     Failure/Error: first_post = Comment.create(comment_content)
     ActiveRecord::StatementInvalid:
       PG::Error: ERROR:  relation "comments" does not exist
       LINE 5:              WHERE a.attrelid = '"comments"'::regclass
                                               ^
       :             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                            pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                     FROM pg_attribute a LEFT JOIN pg_attrdef d
                       ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                    WHERE a.attrelid = '"comments"'::regclass
                      AND a.attnum > 0 AND NOT a.attisdropped
                    ORDER BY a.attnum
     # ./spec/comment_spec.rb:14:in `block (2 levels) in <top (required)>'

Finished in 0.26528 seconds
2 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/comment_spec.rb:4 # Comment should have user_id, a post_id, a time created, and a content
Taras-MacBook-Air:hacker_news tlroys$ RACK_ENV=test rake db:migrate
==  CreateComments: migrating =================================================
-- create_tables(:comments)
rake aborted!
An error has occurred, this and all later migrations canceled:

undefined method `create_tables' for #<CreateComments:0x007f98a6eb6478>
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:465:in `block in method_missing'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:438:in `block in say_with_time'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:438:in `say_with_time'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:458:in `method_missing'
/Users/tlroys/Desktop/ThursdayProjects/hacker_news/db/migrate/20140228093656_create_comments.rb:3:in `change'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:407:in `block (2 levels) in migrate'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:407:in `block in migrate'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:389:in `migrate'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:528:in `migrate'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:775:in `call'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/transactions.rb:208:in `transaction'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:775:in `ddl_transaction'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:719:in `block in migrate'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:700:in `each'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:700:in `migrate'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:570:in `up'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:551:in `migrate'
/Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile:105:in `block (2 levels) in <top (required)>'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `eval'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Taras-MacBook-Air:hacker_news tlroys$ RACK_ENV=test rake db:migrate
==  CreateComments: migrating =================================================
-- create_table(:comments)
   -> 0.0106s
==  CreateComments: migrated (0.0115s) ========================================

Taras-MacBook-Air:hacker_news tlroys$ rspec
*F........*

Pending:
  Join Table Associations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Comment should have user_id, a post_id, a time created, and a content
     Failure/Error: expect(first_post.title).to eq("First Post")
     NoMethodError:
       undefined method `title' for #<Comment:0x007fac528f3648>
     # ./spec/comment_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 1.81 seconds
11 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/comment_spec.rb:4 # Comment should have user_id, a post_id, a time created, and a content
Taras-MacBook-Air:hacker_news tlroys$ rspec
*.........*

Pending:
  Join Table Associations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Finished in 3.45 seconds
11 examples, 0 failures, 2 pending
Taras-MacBook-Air:hacker_news tlroys$ rake db:hard_reset
Dropping database hacker_news_test...
Creating database hacker_news_test if it doesn't exist...
==  CreateUsers: migrating ====================================================
-- create_table(:users)
   -> 0.0066s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0055s
==  CreateUsers: migrated (0.0148s) ===========================================

==  CreatePosts: migrating ====================================================
-- create_table(:posts)
   -> 0.0074s
==  CreatePosts: migrated (0.0082s) ===========================================

==  CreateComments: migrating =================================================
-- create_table(:comments)
   -> 0.0076s
==  CreateComments: migrated (0.0082s) ========================================

Taras-MacBook-Air:hacker_news tlroys$ rspec
*.........*

Pending:
  Join Table Associations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Finished in 1.78 seconds
11 examples, 0 failures, 2 pending
Taras-MacBook-Air:hacker_news tlroys$