How do I create a new post model?
Following the rpsec errors in order to make sure I've done everything is like a game!

Testing is like a game!

Last login: Fri Feb 28 09:16:45 on ttys000
Taras-MacBook-Air:~ tlroys$ ls
3dModels
7357584
ApophysisUserManual
BadassWarriors(WhoWereCats).rtf
BeerSaveTheWorld.rtf
ColorModels.rtf
CrazyWaysToRecycleBodilyFluids.rtf
CreativeUsesOfMummies.rtf
CreepyCloneArmies.rtf
Desktop
Desktops
Documents
Downloads
Dropbox
Eric On animation
FamousGradeSchoolImages.rtf
Finances
HistoryTwitterAccounts.rtf
HorrificallyCreativeUsesOfMummies.pdf
InnocentPeopleGuiltyOfHorribleCrimes.rtf
JobsWhiteGuysStole.rtf
Library
LivesSavedByPoop.rtf
Movies
Music
OpenSource
Personal
Pictures
Plain_svg.svg
Pouf.rtf
PresidentsTorturedToDeath.rtf
ProgramTweets.rtf
Public
Random params 1.chaos
Random params 2.chaos
Salamanders
Screencasts
Socrates
Survey
TarasBlog
Untitled.rtf
UsedAsInk.rtf
ZeroPrivacy.rtf
bin
chaotica
code
flashcard.rb
fractals
gisttest
inkscapeStuff
local
names.rb
pear
public_vs_private
recyclingMethodsFullOfShit.rtf
root@tararoys.com~
ruby_flashcards
src
tara
temp
the_self_keyword
tmp
writing
Taras-MacBook-Air:~ tlroys$ cd ~/Desktop
ruby-2.0.0-p247 is not installed.
To install do: 'rvm install ruby-2.0.0-p247'
Taras-MacBook-Air:Desktop tlroys$ ls
Daily
Downloading an Entire Web Site with wget   Linux Journal_files
GiantFolderOfDoom
ThursdayProjects
ThursdayTwilio
installfest
ruby_drills
safehouse_sitting
twilio
www.linuxjournal.com
Taras-MacBook-Air:Desktop tlroys$ cd ThursdayProjects/
Taras-MacBook-Air:ThursdayProjects tlroys$ ls
HackerNewsLogs    hacker_news   message_app_with_greg
Taras-MacBook-Air:ThursdayProjects tlroys$ cd hacker_news/
Taras-MacBook-Air:hacker_news tlroys$ ls
Gemfile   README.md app   config.ru public
Gemfile.lock  Rakefile  config    db    spec
Taras-MacBook-Air:hacker_news tlroys$ subl .
Taras-MacBook-Air:hacker_news tlroys$ rake generate:spec NAME="associations"
Creating /Users/tlroys/Desktop/ThursdayProjects/hacker_news/spec/associations_spec.rb
Taras-MacBook-Air:hacker_news tlroys$ rspec
*
An error occurred in an after hook
  ActiveRecord::StatementInvalid: PG::Error: ERROR:  relation "posts" does not exist
LINE 1: DELETE FROM "posts"
                    ^
: DELETE FROM "posts"
  occurred at /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `async_exec'

F.......*

Pending:
  Join Table <As></As>sociations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Post should have a title, a content, and a user id
     Failure/Error: user_id: User.create("tara@tara.com", password: "password").id
     NoMethodError:
       undefined method `stringify_keys' for "tara@tara.com":String
     # ./spec/post_spec.rb:13:in `block (2 levels) in <top (required)>'

Finished in 1.54 seconds
10 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/post_spec.rb:9 # Post should have a title, a content, and a user id
Taras-MacBook-Air:hacker_news tlroys$ rspec
*
An error occurred in an after hook
  ActiveRecord::StatementInvalid: PG::Error: ERROR:  relation "posts" does not exist
LINE 1: DELETE FROM "posts"
                    ^
: DELETE FROM "posts"
  occurred at /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `async_exec'

F.......*

Pending:
  Join Table <As></As>sociations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Post should have a title, a content, and a user id
     Failure/Error: first_post = Post.create(content)
     ActiveRecord::StatementInvalid:
       PG::Error: ERROR:  relation "posts" does not exist
       LINE 5:              WHERE a.attrelid = '"posts"'::regclass
                                               ^
       :             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                            pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                     FROM pg_attribute a LEFT JOIN pg_attrdef d
                       ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                    WHERE a.attrelid = '"posts"'::regclass
                      AND a.attnum > 0 AND NOT a.attisdropped
                    ORDER BY a.attnum
     # ./spec/post_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 1.57 seconds
10 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/post_spec.rb:9 # Post should have a title, a content, and a user id
Taras-MacBook-Air:hacker_news tlroys$ rake generate:migration NAME="create_posts"
Creating /Users/tlroys/Desktop/ThursdayProjects/hacker_news/db/migrate/20140228092158_create_posts.rb
Taras-MacBook-Air:hacker_news tlroys$ rspec
*
An error occurred in an after hook
  ActiveRecord::StatementInvalid: PG::Error: ERROR:  relation "posts" does not exist
LINE 1: DELETE FROM "posts"
                    ^
: DELETE FROM "posts"
  occurred at /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `async_exec'

F.......*

Pending:
  Join Table <As></As>sociations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Post should have a title, a content, and a user id
     Failure/Error: first_post = Post.create(content)
     ActiveRecord::StatementInvalid:
       PG::Error: ERROR:  relation "posts" does not exist
       LINE 5:              WHERE a.attrelid = '"posts"'::regclass
                                               ^
       :             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                            pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                     FROM pg_attribute a LEFT JOIN pg_attrdef d
                       ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                    WHERE a.attrelid = '"posts"'::regclass
                      AND a.attnum > 0 AND NOT a.attisdropped
                    ORDER BY a.attnum
     # ./spec/post_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 1.59 seconds
10 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/post_spec.rb:9 # Post should have a title, a content, and a user id
Taras-MacBook-Air:hacker_news tlroys$ RACK_ENV=text rake db:migrate
rake aborted!
FATAL:  database "hacker_news_text" does not exist
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1208:in `initialize'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1208:in `new'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1208:in `connect'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:326:in `initialize'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `new'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `postgresql_connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:662:in `initialize'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:570:in `new'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:570:in `up'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/activerecord-3.2.12/lib/active_record/migration.rb:551:in `migrate'
/Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile:105:in `block (2 levels) in <top (required)>'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `eval'
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Taras-MacBook-Air:hacker_news tlroys$ RACK_ENV=test rake db:migrate
==  CreatePosts: migrating ====================================================
-- create_table(:posts)
   -> 0.0692s
==  CreatePosts: migrated (0.0698s) ===========================================

Taras-MacBook-Air:hacker_news tlroys$ rspec
*........*

Pending:
  Join Table <As></As>sociations add some examples to (or delete) /Users/tlroys/Desktop/ThursdayProjects/hacker_news/Rakefile
    # No reason given
    # ./spec/associations_spec.rb:4
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Finished in 1.6 seconds
10 examples, 0 failures, 2 pending
Taras-MacBook-Air:hacker_news tlroys$ git add -p
No changes.
Taras-MacBook-Air:hacker_news tlroys$ git add spec/post_spec.rb
Taras-MacBook-Air:hacker_news tlroys$ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

  new file:   spec/post_spec.rb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

  app/models/post.rb
  db/migrate/20140228092158_create_posts.rb
  spec/associations_spec.rb

Taras-MacBook-Air:hacker_news tlroys$ git add app/models/post.rb
Taras-MacBook-Air:hacker_news tlroys$ git add db/migrate/20140228092158_create_posts.rb
Taras-MacBook-Air:hacker_news tlroys$ git commit
[master d0cb526] How do I create a new post model?
 3 files changed, 33 insertions(+)
 create mode 100644 app/models/post.rb
 create mode 100644 db/migrate/20140228092158_create_posts.rb
 create mode 100644 spec/post_spec.rb
Taras-MacBook-Air:hacker_news tlroys$