How do I set up a testing suite for join table assoications
Like this!

Last login: Fri Feb 28 09:45:44 on ttys000
ruby-2.0.0-p247 is not installed.
To install do: 'rvm install ruby-2.0.0-p247'
Taras-MacBook-Air:hacker_news tlroys$ rspec
/Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load': /Users/tlroys/Desktop/ThursdayProjects/hacker_news/spec/associations_spec.rb:17: syntax error, unexpected ')', expecting tASSOC (SyntaxError)
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `block in load_spec_files'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `each'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/configuration.rb:789:in `load_spec_files'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/command_line.rb:22:in `run'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:80:in `run'
  from /Users/tlroys/.rvm/gems/ruby-1.9.3-p484/gems/rspec-core-2.12.2/lib/rspec/core/runner.rb:17:in `block in autorun'
Taras-MacBook-Air:hacker_news tlroys$ l
-bash: l: command not found
Taras-MacBook-Air:hacker_news tlroys$ ls
Gemfile   README.md app   config.ru public
Gemfile.lock  Rakefile  config    db    spec
Taras-MacBook-Air:hacker_news tlroys$ ls
Gemfile   README.md app   config.ru public
Gemfile.lock  Rakefile  config    db    spec
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(true).to eq(false);

       expected: false
            got: true

       (compared using ==)
     # ./spec/associations_spec.rb:20:in `block (3 levels) in <top (required)>'

Finished in 2.12 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:6 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(true).to eq(false);

       expected: false
            got: true

       (compared using ==)
     # ./spec/associations_spec.rb:27:in `block (3 levels) in <top (required)>'

Finished in 2.07 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:13 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(zoe.posts.count).to eq(2) #user has many proficiencies
     NoMethodError:
       undefined method `posts' for #<User:0x007fc0d3337318>
     # ./spec/associations_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 2.15 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:13 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(zoe.posts.count).to eq(2) #user has many proficiencies
     ActiveRecord::HasManyThroughSourceAssociationNotFoundError:
       Could not find the source association(s) :post or :posts in model Comment. Try 'has_many :posts, :through => :comments, :source => <name>'. Is it one of ?
     # ./spec/associations_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 2.14 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:13 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(zoe.posts.count).to eq(2) #user has many proficiencies
     NameError:
       uninitialized constant User::Posts
     # ./spec/associations_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 2.14 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:13 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(zoe.posts.count).to eq(2)
     NameError:
       uninitialized constant User::Posts
     # ./spec/associations_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 2.26 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:13 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(zoe.posts.count).to eq(2)
     NameError:
       uninitialized constant User::Posts
     # ./spec/associations_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 2.16 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:13 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(hate_the_alliance.users).to eq(2)
     NoMethodError:
       undefined method `users' for #<Post:0x007fa5b2c601b0>
     # ./spec/associations_spec.rb:31:in `block (3 levels) in <top (required)>'

Finished in 2.18 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:13 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
F.........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Failures:

  1) Join Table Associations create associations tests that all of the associations for the join table are set up correctly
     Failure/Error: expect(hate_the_alliance.users).to eq(2)

       expected: 2
            got: [#<User id: 86, email: "zoe@serenity.com", password_hash: "$2a$10$/ChxiWougoiHZ8DaLXHGvOYFD2xUiRW43G2dgco0RjK6...">, #<User id: 87, email: "inara@serenity.com", password_hash: "$2a$10$7OUqhEf6FDcO88Ind/A.4OETBq5p.kDbJiz3PfxldF6T...">]

       (compared using ==)
     # ./spec/associations_spec.rb:31:in `block (3 levels) in <top (required)>'

Finished in 2.15 seconds
11 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/associations_spec.rb:13 # Join Table Associations create associations tests that all of the associations for the join table are set up correctly
Taras-MacBook-Air:hacker_news tlroys$ rspec
..........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Finished in 2.17 seconds
11 examples, 0 failures, 1 pending
Taras-MacBook-Air:hacker_news tlroys$ rspec
..........*

Pending:
  User You should have a password
    # Temporarily disabled with xit
    # ./spec/user_spec.rb:63

Finished in 2.21 seconds
11 examples, 0 failures, 1 pending
Taras-MacBook-Air:hacker_news tlroys$